`timescale 1ns / 1ps
//-----------------------------------------------------------------------------------------
//Module: data_memory
//Description: 
//	Word-addressed data memory used by the CPU datapath. The module
//	accepts a byte-based address and internally converts it to a word
//	index 
//Assumptions:
//	- addr is a byte address generated by the ALU.
//	- memory is organized as 32-bit words.
//	- only word-aligned accesses are expected.
//Notes:
//	- the byte-to-word address conversion drops the two LSBs of addr.
//	- address alignment and bounds checking will be enforced via
//	  assertions in a later verification stage 
//-----------------------------------------------------------------------------------------
module data_memory #(
    parameter DATA_WIDTH =32,
    parameter DEPTH = 1024
)(
    input  logic        clk,
    input  logic        wr_en,
    input  logic [DATA_WIDTH-1:0] addr,      // byte address (ALU result)
    input  logic [DATA_WIDTH-1:0] data_in,   // store data (rs2)
    output logic [DATA_WIDTH-1:0] data_out   // raw 32-bit word read
);

    logic [31:0] mem [0:DEPTH-1];

    // Word index: byte address -> word address (drop 2 LSBs)
    logic [$clog2(DEPTH)-1:0] word_idx;
    assign word_idx = addr[11:2];  // for DEPTH=1024 (4KB), safe indexing

    // Combinational read 
    assign data_out = mem[word_idx];

    // Synchronous write
    always_ff @(posedge clk) begin
        if (wr_en) begin
            mem[word_idx] <= data_in;
        end
    end

endmodule
